### ISSUE TITLE
Unable to operate（Windows）

### ISSUE THREAD

**Issue by sususuuu** [domneedham/pico-clock-green-python#24]
Hello, I tried to open Thonny on windows to run your code and got the following error:
>>> %Run -c $EDITOR_CONTENT

MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "display.py", line 5, in <module>
  File "util.py", line 13, in inner
SyntaxError: can't have multiple *x
>>> 

As a result, I cannot use this excellent example code, which bothers me very much. I hope you can have some time to help me point out the solution direction, thank you very much!

**Comment by domneedham** [comment]
Sadly I'm not too sure. I don't have a Windows machine I can use to even suggest what could be wrong...
