### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by didi2sk** [domneedham/pico-clock-green-python#25]
When I enable MQTT program crash.

**Comment by didi2sk** [comment]
Traceback (most recent call last):
  File "<stdin>", line 35, in <module>
  File "util.py", line 6, in getinstance
  File "mqtt.py", line 31, in __init__
  File "mqtt.py", line 45, in connect
  File "/lib/umqtt/simple.py", line 154, in subscribe
  File "/lib/umqtt/simple.py", line 173, in wait_msg
OSError: -1

**Comment by domneedham** [comment]
Been a long time since I've looked at this. Might be a dependency issue where the version installed is too new?

**Comment by didi2sk** [comment]
Hi,
yes there was problem width dependecy mqtt library  and severeal other error. In critical peaces of code I use try: and make a lot other change. I reading temperature from external zigbee temp. sensors and show it on clock
